apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: lavan2devops@gmail.com
    privateKeySecretRef:
      name: chart-example-tls
    solvers:
      - http01:
          ingress: {}
