---
# Source: hello-world-chart/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello-world-app-hello-world-chart
  labels:
    helm.sh/chart: hello-world-chart-0.1.0
    app.kubernetes.io/name: hello-world-chart
    app.kubernetes.io/instance: hello-world-app
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: hello-world-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: hello-world-app-hello-world-chart
  labels:
    helm.sh/chart: hello-world-chart-0.1.0
    app.kubernetes.io/name: hello-world-chart
    app.kubernetes.io/instance: hello-world-app
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8082  # Exposing the service on port 8082
      targetPort: 8082  # Pointing to the correct container port
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: hello-world-chart
    app.kubernetes.io/instance: hello-world-app
---
# Source: hello-world-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app-hello-world-chart
  labels:
    helm.sh/chart: hello-world-chart-0.1.0
    app.kubernetes.io/name: hello-world-chart
    app.kubernetes.io/instance: hello-world-app
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-world-chart
      app.kubernetes.io/instance: hello-world-app
  template:
    metadata:
      labels:
        helm.sh/chart: hello-world-chart-0.1.0
        app.kubernetes.io/name: hello-world-chart
        app.kubernetes.io/instance: hello-world-app
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: hello-world-app-hello-world-chart
      containers:
        - name: hello-world-chart
          image: "lavanya0421/springboot-helloworld:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8082  # Explicitly set port 8082 for Spring Boot
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082  # Correct port for the liveness probe
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082  # Correct port for the readiness probe
            initialDelaySeconds: 5
            periodSeconds: 5
---
# Source: hello-world-chart/templates/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hello-world-app-hello-world-chart
  labels:
    helm.sh/chart: hello-world-chart-0.1.0
    app.kubernetes.io/name: hello-world-chart
    app.kubernetes.io/instance: hello-world-app
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-world-app-hello-world-chart
  minReplicas: 1
  maxReplicas: 100
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
---
# Source: hello-world-chart/templates/Chart.yaml
apiVersion: v2
name: hello-world-chart
description: A Helm chart for deploying the Hello World application
version: 0.1.0
appVersion: 1.0.0
---
# Source: hello-world-chart/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "hello-world-app-hello-world-chart-test-connection"
  labels:
    helm.sh/chart: hello-world-chart-0.1.0
    app.kubernetes.io/name: hello-world-chart
    app.kubernetes.io/instance: hello-world-app
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['hello-world-app-hello-world-chart:80']
  restartPolicy: Never
